# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Clayton Errington – Web & Software Developer
email:
description: Specialized web designer and software developer
twitter_username: cjerrington
github_username: cjerrington
minimal_mistakes_skin: dark
search: true

head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
  - /assets/js/custom.js

repository: "cjerrington/cjerrington.github.io"

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - .well-known
  - assets
  - _includes
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Clayton Errington"
  avatar : "../images/avatar2.jpg"
  bio    : "Specialized web designer and software developer"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://claytonerrington.com"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mstdn.social/@cjerrington"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cjerrington"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cjerrington/"
    - label: "Codeberg"
      icon: "fab fa-fw fa-git-alt"
      url: "https://codeberg.org/cjerrington"
      
footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mstdn.social/@cjerrington"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cjerrington"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cjerrington"
    - label: "Codeberg"
      icon: "fab fa-fw fa-git-alt"
      url: "https://codeberg.org/cjerrington"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      
# Analytics
analytics:
  provider               : google-gtag # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : G-3H2MXCJ0FW
    anonymize_ip         : # true, false (default)

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/