source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: ../static
  includes: _includes
  pages: pages
collections_config:
  post:
    path: posts
    output: true
    icon: notes
    add_options:
      - name: Add Post
        editor: content
    create:
      extra_data:
        filename: '{date|year}-{date|month}-{date|day}-{title}'
      path: '[relative_base_path]/{filename|slugify}.md'
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    filter:
      exclude:
        - posts.json
    schemas:
      default:
        path: src/_schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  drafts:
    path: drafts
    output: true
    icon: notes
    add_options:
      - name: Add Draft
        editor: content
    create:
      extra_data:
        filename: '{date|year}-{date|month}-{date|day}-{title}'
      path: '[relative_base_path]/{filename|slugify}.md'
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    filter:
      exclude:
        - drafts.json
    schemas:
      default:
        path: src/_schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
main_content: 
_inputs:
  main_content:
    type: markdown
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: /css/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true

_select_data: {}
_structures: {}
_editables: {}
data_config: {}
editor: {}
source_editor:
  tab_size: 2
  theme: nord_dark
  show_gutter: true
timezone: Etc/UTC
