source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  post:
    path: posts
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    add_options:
      - name: Add Post
        editor: content
    schemas:
      default:
        path: src/_schemas/post.md
  drafts:
    path: drafts
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    add_options:
      - name: Add Draft
        editor: content
    schemas:
      default:
        path: src/_schemas/post.md
  data:
    path: _data
    output: false
    icon: notes
    disable_add: true
    disable_add_folder: false
    disable_file_actions: false
_inputs: 
  layout:
    hidden: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
source_editor:
  tab_size: 2
  theme: nord_dark
  show_gutter: true
timezone: Etc/UTC
