[[redirects]]
  from = "https://cjerrington.netlify.app/"
  to = "https://claytonerrington.com"
  status = 301
  force = true

[[redirects]]
  from = "https://cjerrington.github.io/"
  to = "https://claytonerrington.com"
  status = 301
  force = true